version: '3.9'

services:
  app:
    build: .
    env_file: .env
    network_mode: bridge
    working_dir: /app
    command: >
        bash -c "pm2 start bot.py --update-env --name music_quiz --interpreter python3 &&
                pm2 logs -f"
